<h3>LIBRARY</h3>

In [1]:
import pandas as pd
import numpy as np

<h3>PEMBACAAN DATASET</h3>

In [2]:
data = pd.read_csv("dataset/EE_data_baru.csv", index_col=0)
data.head()

country   ppl_acc  ppl_no_acc   e_non_ebt     e_ebt      e_co2_em
0  Algeria  25464440      447927  314.574536  0.355263  3.463348e+07
1  Algeria  26123557      430772  311.228686  0.771053  3.467090e+07
2  Algeria  26768936      412158  319.638446  0.523684  3.498281e+07
3  Algeria  27393494      392765  296.951167  0.928947  3.654737e+07
4  Algeria  27988776      373477  301.430246  0.436842  3.936556e+07

In [3]:
data.shape

(1938, 6)

<h3>OLAH DATA X & Y</h3>

In [4]:
data = data.dropna()
data = data.drop(columns = ['country'])
data.shape

(1888, 5)

In [5]:
x = data.drop(columns = ['e_co2_em']) #mengambil semua data kecuali emisi karbon dari listrik
y = data['e_co2_em'] #data emisi karbon dari listrik
x2 = data.drop(columns = ['e_ebt', 'e_non_ebt']) #ambil semua data kecuali produksi listrik
y2 = data.drop(columns = ['ppl_acc', 'ppl_no_acc', 'e_co2_em']) #ambil semua data kecuali akses listrik dan emisi

<h3>MEMBAGI DATA UNTUK TRAIN & TEST</h3>

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
X2_train, X2_test, Y2_train, Y2_test = train_test_split(x2, y2, test_size = 0.2, random_state = 0)

<h3>REGRESI LINIER</h3>

Memanggil library dan melakukan fitting

In [7]:
from sklearn.linear_model import LinearRegression
linRegressor = LinearRegression()
linRegressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
linRegressor2 = LinearRegression()
linRegressor2.fit(X2_train, Y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Melakukan test (prediksi)

In [9]:
Y_predCO2_1 = linRegressor.predict(X_test)

In [10]:
Y_predListrik_1 = linRegressor2.predict(X2_test)

Akurasi dari test (koefisien determinasi)

In [11]:
print('Akurasi prediksi emisi CO2:', linRegressor.score(X_test, Y_test)*100, "%")
print('Akurasi prediksi produksi listrik:', linRegressor2.score(X2_test, Y2_test)*100, "%")
#akurasi test

Akurasi prediksi emisi CO2: 99.67118490348595 %
Akurasi prediksi produksi listrik: 99.5736199838812 %


c:\users\sei\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


Hasil prediksi

In [12]:
Y_predCO2_1[0]
#hanya di print yang index 0 untuk mempersingkat output notebook saja

27064197.482877895

In [13]:
Y_predListrik_1[0]

array([486.85130011,  30.31849228])

<h3>REGRESI K NEIGHBOR</h3>

Memanggil library dan melakukan pengaturan jumlah neighbor dan metric yang digunakan

In [14]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3, metric='euclidean')
neigh2 = KNeighborsRegressor(n_neighbors=1, metric='euclidean')

In [15]:
neigh.fit(X_train, Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='euclidean',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

In [16]:
neigh2.fit(X2_train, Y2_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='euclidean',
                    metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                    weights='uniform')

Melakukan prediksi dan mengkalkulasi akurasi hasil prediksi / test

In [17]:
Y_predCO2_2 = neigh.predict(X_test)
print('Akurasi prediksi emisi CO2:', neigh.score(X_test, Y_test)*100, "%")
Y_predListrik_2 = neigh2.predict(X2_test)
print('Akurasi prediksi produksi lisrik:', neigh2.score(X2_test, Y2_test)*100, "%")

Akurasi prediksi emisi CO2: 99.65119798694417 %
Akurasi prediksi produksi lisrik: 99.92870334408262 %


c:\users\sei\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


Mencetak hasil prediksi

In [18]:
Y_predCO2_2[0]

21635164.36411867

In [19]:
Y_predListrik_2[0]

array([3.33169754e+02, 5.00000000e-02])

<h3>REGRESI RIDGE</h3>

Memanggil library dan melakukan fitting

In [20]:
from sklearn.linear_model import Ridge

In [21]:
ridgeRegressor = Ridge()
ridgeRegressor.fit(X_train, Y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [22]:
ridgeRegressor2 = Ridge()
ridgeRegressor2.fit(X2_train, Y2_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

Melakukan test (prediksi)

In [23]:
Y_predCO2_3 = ridgeRegressor.predict(X_test)

In [24]:
Y_predListrik_3 = ridgeRegressor2.predict(X2_test)

Akurasi dari test (koefisien determinasi)

In [25]:
print('Akurasi prediksi emisi CO2:', ridgeRegressor.score(X_test, Y_test)*100, "%")
print('Akurasi prediksi produksi listrik:', ridgeRegressor2.score(X2_test, Y2_test)*100, "%")
#akurasi test

Akurasi prediksi emisi CO2: 99.67118490347482 %
Akurasi prediksi produksi listrik: 99.5736199838812 %


c:\users\sei\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


Hasil prediksi

In [26]:
Y_predCO2_3[0]
#hanya di print yang index 0 untuk mempersingkat output notebook saja

27064197.489905715

In [27]:
Y_predListrik_3[0]

array([486.85130011,  30.31849228])

<h3>PREDIKSI MENGGUNAKAN INPUT PENGGUNA (semua regresi)</h3>

Menerima input dari user untuk prediksi emisi karbon

In [23]:
print('Populasi dengan akses : ')
ppl_acc = input()
print('Populasi tanpa akses listrik: ')
ppl_no_acc = input()
print('Produksi listrik non ebt (TWh): ')
e_non_ebt = input()
print('Produksi listrik ebt (TWh)')
e_ebt = input()

Populasi dengan akses listrik: 
10000
Populasi tanpa akses listrik: 
5000
Produksi listrik non ebt (TWh): 
100
Produksi listrik ebt (TWh)
50


In [29]:
ppl_acc = 6232831242
ppl_no_acc = 1038491579
e_non_ebt = 136554.
e_ebt = 013934.85412
true_co2_em = 17412127356
#data world idx terakhir

Prediksi dari input user

In [30]:
predDataEm1 = linRegressor.predict(pd.DataFrame(
    [[ppl_acc, ppl_no_acc, e_non_ebt, e_ebt]]))[0]
print("linier, CO2:",predDataEm1, 'ton') #linier

predDataEm2 = neigh.predict(pd.DataFrame(
    [[ppl_acc, ppl_no_acc, e_non_ebt, e_ebt]]))[0]
print("kNN, CO2:",predDataEm2, 'ton') #kNN

predDataEm3 = ridgeRegressor.predict(pd.DataFrame(
    [[ppl_acc, ppl_no_acc, e_non_ebt, e_ebt]]))[0]
print("ridge, CO2:",predDataEm3, 'ton') #ridge

linier, CO2: 17174233003.089338 ton
kNN, CO2: 16626729937.078962 ton
ridge, CO2: 17174233000.93338 ton


Error  relatif dari prediksi emisi karbon

In [31]:
print('Error relatif CO2 (linier):', abs(true_co2_em-predDataEm1)/true_co2_em*100,"%")
print('Error relatif CO2 (kNN):', abs(true_co2_em-predDataEm2)/true_co2_em*100,"%")
print('Error relatif CO2 (ridge):', abs(true_co2_em-predDataEm3)/true_co2_em*100,"%")

Error relatif CO2 (linier): 1.366256678731943 %
Error relatif CO2 (kNN): 4.510634472532729 %
Error relatif CO2 (ridge): 1.3662566911138774 %


Menerima input dari user untuk prediksi produksi listrik

In [29]:
print('Populasi dengan akses listrik: ')
ppl_acc = input()
print('Populasi tanpa akses listrik: ')
ppl_no_acc = input()
print('Goal emisi karbon (ton): ')
e_co2_em = input()

Populasi dengan akses listrik: 
2000
Populasi tanpa akses listrik: 
1000
Goal emisi karbon (ton): 
100


In [32]:
ppl_acc = 6232831242
ppl_no_acc = 1038491579
e_co2_em = 17412127356
true_PL = [136554.648, 013934.85412]
#data world idx terakhir

Prediksi dari input user

In [33]:
predDataPL1 = linRegressor2.predict(pd.DataFrame([[ppl_acc, ppl_no_acc, e_co2_em]]))[0]
print("linier, listrik:", predDataPL1, 'TWh')

predDataPL2 = neigh2.predict(pd.DataFrame([[ppl_acc, ppl_no_acc, e_co2_em]]))[0]
print("kNN, listrik:", predDataPL2, 'TWh')

predDataPL3 = ridgeRegressor2.predict(pd.DataFrame([[ppl_acc, ppl_no_acc, e_co2_em]]))[0]
print("ridge, listrik:", predDataPL3, 'TWh')

linier, listrik: [139599.25599337  10911.46836603] TWh
kNN, listrik: [135822.429782   13267.5000285] TWh
ridge, listrik: [139599.25599337  10911.46836603] TWh


Error relatif dari prediksi listrik

In [34]:
print('Error relatif listrik (linier):', abs(true_PL-predDataPL1)/true_PL*100,"%")
print('Error relatif listrik (kNN):', abs(true_PL-predDataPL2)/true_PL*100,"%")
print('Error relatif listrik (ridge):', abs(true_PL-predDataPL3)/true_PL*100,"%")

Error relatif listrik (linier): [ 2.22958943 21.69657269] %
Error relatif listrik (kNN): [0.53620893 4.78909995] %
Error relatif listrik (ridge): [ 2.22958943 21.69657269] %
