In [129]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("energy_impact_upd.csv")
data.head()

Year  Electricity Production (kWh)  Electricity Consumption (kWh/capita)  \
0  1960                           NaN                                   NaN   
1  1961                           NaN                                   NaN   
2  1962                           NaN                                   NaN   
3  1963                           NaN                                   NaN   
4  1964                           NaN                                   NaN   

   Population  CO2 emmission (kt)  Electricity Production from Fossil(kWh)  \
0    87751068           21404.279                                      NaN   
1    90098394           26024.699                                      NaN   
2    92518377           22995.757                                      NaN   
3    95015297           22783.071                                      NaN   
4    97596733           22394.369                                      NaN   

   Electricity Production Renewable (kWh)  CO2 Emission from Electricity (kt)  
0                                     NaN                                 NaN  
1                                     NaN                                 NaN  
2                                     NaN                                 NaN  
3                                     NaN                                 NaN  
4                                     NaN                                 NaN

In [128]:
data.columns = ['year','e_production','e_use','population', 'total_co2', 'e_fossil', 'e_renewable', 'e_co2']
data.shape

(59, 8)

In [157]:
data_tanpa_NaN = data[(data["year"]>=1982) & (data["year"]<=2013)]

x = data_tanpa_NaN.loc[:, ['e_production','e_use','population', 'total_co2', 'e_fossil', 'e_renewable']] #mengambil semua data kecuali emisi karbon dari listrik
y = data_tanpa_NaN["e_co2"] #data emisi karbon dari listrik
#X = data_tanpa_NaN.iloc[:,:-1].values
#Y = data_tanpa_NaN.iloc[:, 7].values
#X=X[:, 1:]

data_tanpa_NaN.head()

year  e_production       e_use  population   total_co2      e_fossil  \
22  1982  1.057200e+10   66.097398   154468229  105407.915  9.176000e+09   
23  1983  1.211000e+10   71.444780   158009246  104956.874  1.008500e+10   
24  1984  1.362200e+10   79.759998   161523347  112184.531  1.128700e+10   
25  1985  1.409800e+10   92.056811   164982451  121245.688  1.088400e+10   
26  1986  1.950700e+10  104.354756   168374287  121740.733  1.424500e+10   

     e_renewable        e_co2  
22  1.396000e+09  20053.82449  
23  2.025000e+09  20251.41910  
24  2.335000e+09  27438.50314  
25  3.214000e+09  30018.75003  
26  5.262000e+09  32416.40289

In [158]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [159]:
from sklearn.linear_model import LinearRegression
linRegressor = LinearRegression()
linRegressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [160]:
Y_predCO2_1 = linRegressor.predict(X_test)

In [161]:
print(linRegressor.score(X_test, Y_test)*100, "%")
#akurasi test

98.1582974927268 %


In [162]:
Y_predCO2_1

array([ 79158.02392993, 132362.88794583,  71596.84226201,  27023.00367716,
        73713.92009018,  94479.37168653, 174792.21318207])

In [188]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=1, metric='euclidean')

In [189]:
neigh.fit(X_train, Y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='euclidean',
                    metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                    weights='uniform')

In [190]:
Y_predCO2_2 = neigh.predict(X_test)
print(neigh.score(X_test, Y_test)*100, "%")
Y_predCO2_2

95.50538253472213 %


array([ 79157.66636, 124631.4509 ,  67159.89897,  30018.75003,
       104647.4794 ,  81800.77543, 180780.1621 ])

In [191]:
print(neigh.predict(pd.DataFrame([[1000000000,1000000000,1000000000,1000000000,1000000000,1000000000]]))[0])

20053.82449


In [168]:
x2 = data_tanpa_NaN.loc[:,['e_production','e_use','population', 'total_co2', 'e_co2']]
y2 = data_tanpa_NaN.loc[:,['e_fossil', 'e_renewable']]
#X2 = x2.values
#Y2 = y2.values
#X2=X2[:, 1:]

In [169]:
X2_train, X2_test, Y2_train, Y2_test = train_test_split(x2, y2, test_size = 0.2, random_state = 0)
linRegressor2 = LinearRegression()
linRegressor2.fit(X2_train, Y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [170]:
Y_predListrik = linRegressor2.predict(X2_test)
print(linRegressor2.score(X2_test, Y2_test)*100, "%")

99.42692989401972 %


c:\users\sei\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [171]:
Y_predListrik

array([[3.75243440e+10, 7.92135854e+09],
       [1.03544015e+11, 1.64695742e+10],
       [3.39177134e+10, 7.65526958e+09],
       [1.03491014e+10, 3.27931306e+09],
       [6.53757227e+10, 1.26267023e+10],
       [5.77639109e+10, 9.95071939e+09],
       [1.48336944e+11, 2.16486161e+10]])

In [184]:
neigh2 = KNeighborsRegressor(n_neighbors=1, metric='euclidean')

In [185]:
neigh2.fit(X2_train, Y2_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='euclidean',
                    metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                    weights='uniform')

In [186]:
Y2_predListrik = neigh2.predict(X2_test)
print(neigh2.score(X2_test, Y2_test)*100, "%")
Y2_predListrik

97.59966060166569 %


c:\users\sei\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


array([[4.33170000e+10, 8.04100023e+09],
       [9.75660000e+10, 1.54080003e+10],
       [2.96640000e+10, 7.67600009e+09],
       [1.08840000e+10, 3.21400002e+09],
       [6.69110000e+10, 7.71600022e+09],
       [6.69110000e+10, 7.71600022e+09],
       [1.36028000e+11, 2.07459993e+10]])

In [187]:
print(neigh2.predict(pd.DataFrame([[1000000000,1000000000,1000000000,1000000000,1000000000]]))[0])

[9.176e+09 1.396e+09]
